DROP TABLE admins;
DROP TABLE students;
DROP TABLE courses;
DROP TABLE grading_system;
DROP TABLE costs;
DROP TABLE credit_limits;
DROP TABLE semesters;
DROP TABLE requests;
DROP TABLE prerequisites;